default_language_version:
  python: python3
fail_fast: true

exclude: |
  (?x)^(
      .*?src/.* |
      .*?/migrations/.* |
      .*?/?__pycache__/.* |
      .git/.* |
      .mypy_cache/.* |
      .pytest_cache/.* |
      .tox/.* |
      .venv/.* |
      .vscode/.* |
      node_modules/.* |
      fh_app_template/.* |
      .*?/*.yml |
      .*?/*.yaml |
      .*?/*.cfg |
      .*?/*.toml
  )$

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
    - id: pyupgrade
      stages: [pre-commit]
      name: "✅ Python Upgrade"
      args:
        - "--py314-plus"
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.30.0
    hooks:
    -   id: django-upgrade
        stages: [pre-commit]
        name: "✅ Django Upgrade"
        args: [--target-version, "5.2"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the ref you want to point at
    hooks:
    - id: check-merge-conflict
      name: "✅ Checking Merge Conflict"
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    - id: black
      stages: [pre-commit]
      name: "✅ Black Reformatting"
      exclude: ^.*\b(migrations)\b.*$
      args: ["--line-length", "79"]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
    - id: autoflake
      stages: [pre-commit]
      name: "✅ Autoflake Reformatting"
      language: python
      'types': [python]
      require_serial: true
      exclude: |
        (?x)(
          .*?/migrations/.*
        )
      entry: autoflake
      args:
        - "--ignore-init-module-imports"
        - "--remove-all-unused-imports"
        - "--in-place"
        - "--remove-unused-variables"
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    - id: flake8
      stages: [pre-commit]
      name: "✅ Flake8 Validation"
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    - id: isort
      stages: [pre-commit]
      name: "✅ Isort Validation"
  - repo: local
    hooks:
    - id: mypy
      stages: [pre-commit]
      name: "✅ Mypy Validation"
      entry: mypy
      language: python
      types: [python]
      args: [
          "--install-types",
          "--non-interactive",
          "--no-namespace-packages",
        ]
      additional_dependencies: [
        "mypy~=1.11.2"
      ]
