[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "soft-delete-model-mixin"
dynamic = ["version"]
description = "A Soft delete model mixin for your Django Model"
readme = "README.rst"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    {name = "FrankHood Business Solutions srl", email = "info@frankhood.it"},
]
keywords = ["soft-delete-model-mixin"]
requires-python = ">=3.11"
dependencies = ["django>=5.2,<5.3"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: Django",
    "Framework :: Django :: 5.2",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

[project.urls]
Homepage = "https://github.com/frankhood/django-soft-delete-model-mixin"

[project.optional-dependencies]
test = [
    "coverage>=7",
    "flake8>=7",
    "tox>=4",
]

[tool.setuptools.dynamic]
version = {attr = "soft_delete_model_mixin.__version__"}

[tool.setuptools.packages.find]
where = ["."]
include = ["soft_delete_model_mixin*"]


[tool.black]
target-version = ["py311"]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    | __pycache__
    | .git
    | .mypy_cache
    | .pytest_cache
    | .tox
    | .venv
    | .vscode
    | node_modules
    | migrations
    | node_modules
)/
'''


# https://pycqa.github.io/isort/docs/configuration/options.html
[tool.isort]
atomic = true
line_length = 120
profile = "black"
combine_as_imports = true
default_section = "THIRDPARTY"
known_third_party = "django"
skip = [
    '.bzr', 
    '.direnv',
    '.eggs', 
    '.git',
    '.hg',
    '.mypy_cache',
    '.nox',
    '.pants.d',
    '.svn',
    '.tox', 
    '.venv', 
    '__pypackages__', 
    '_build',
    'buck-out',
    'build',
    'dist',
    'node_modules',
    'venv',
    'migrations',
]


[tool.mypy]
# python_version = 3.11
ignore_missing_imports = true

exclude = [
    '^.*?src/.*$',
    '^.*?/migrations/.*$',
    '^.*?/factories\.py$',
    "^.*?/?__pycache__/.*$",
    "^.git/.*$",
    "^.mypy_cache/.*$",
    "^.pytest_cache/.*$",
    "^.tox/.*$",
    "^.venv/.*$",
    "^.vscode/.*$",
    "^node_modules/.*$",
    '^.*?/tests/.*$',
]
