[tox]
envlist = py{311,312,313,314}-django52

[testenv]
deps =
    django52: Django>=5.2,<5.3
    -r{toxinidir}/requirements_test.txt
commands = coverage run --source soft_delete_model_mixin runtests.py
